apiVersion: v1
kind: Pod
metadata:
  name: pod-db
spec:
  containers:
  - name: pod-db
    image: 244069240907.dkr.ecr.us-east-1.amazonaws.com/docker-containers-db:v0.1
    ports:
    - containerPort: 3306