apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-db
  labels:
    app: mysql
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: replicaset-db
        image: 244069240907.dkr.ecr.us-east-1.amazonaws.com/docker-containers-db:v0.1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306